otl:
  otel_exporter_otlp_endpoint: my-release-k8s-infra-otel-agent.platform:4317

warden:
  port: 4000
  debug_port: 4005
  member_svc: member.default:5000

member:
  port: 5000
  setting_svc: setting.default:6000

setting:
  port: 6000
  settlement_svc: settlement.default:7000

settlement:
  port: 7000
  core_svc: core.default:8000

core:
  port: 8000




