apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: godebug
  name: godebug
spec:
  selector:
    matchLabels:
      app: godebug
  template:
    metadata:
      labels:
        app: godebug
    spec:
      containers:
        - name: godebug
          args:
          - -c
          - /godebug serve --config /etc/godebug/config.yaml
          command:
          - /bin/sh
          image: godebug:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
#            - containerPort: 8005
          volumeMounts:
          - mountPath: /etc/godebug
            name: godebug-config
      volumes:
      - name: godebug-config
        secret:
          secretName: godebug-config
---
apiVersion: v1
kind: Secret
metadata:
  name: godebug-config
type: Opaque
stringData:
  config.yaml: |
    app:
      port: 8000
      debug_port: 8005
      graceful_timeout: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: godebug
  name: godebug
spec:
  type: NodePort
  ports:
    - name: 8000-tcp
      port: 8000
      targetPort: 8000
      nodePort: 30800
#    - name: 8005-tcp
#      port: 8005
#      targetPort: 8005
#      nodePort: 30805
  selector:
    app: godebug


#app:
#  port: 8000
#  debug_port: 8005
#  graceful_timeout: 30