apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: req
  name: req
spec:
  selector:
    matchLabels:
      app: req
  template:
    metadata:
      labels:
        app: req
    spec:
      containers:
        - name: req
          image: godebug:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6000
          command:
            - "/godebug"
            - "req"
            - "-c"
            - "/config.yaml"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: req
  name: req
spec:
  type: NodePort
  ports:
    - name: 6000-tcp
      port: 6000
      targetPort: 6000
  selector:
    app: req
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: req
#spec:
#  ingressClassName: kong
#  rules:
#    - http:
#        paths:
#          - pathType: Prefix
#            path: "/req"
#            backend:
#              service:
#                name: req
#                port:
#                  number: 6000