apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: request
  name: request
spec:
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
    spec:
      containers:
      - name: request
        image: godebug:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        command:
        - "/godebug"
        - "request"
        - "-c"
        - "/config.yaml"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: request
  name: request
spec:
  type: NodePort
  ports:
    - name: 9000-tcp
      port: 9000
      targetPort: 9000
  selector:
    app: request
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: request
#spec:
#  ingressClassName: kong
#  rules:
#    - http:
#        paths:
#          - pathType: Prefix
#            path: "/request"
#            backend:
#              service:
#                name: request
#                port:
#                  number: 9000