apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: godebug
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: godebug
  endpoints:
    - port: 8000-tcp