apiVersion: v1
kind: Service
metadata:
  name: {{ include "godebug.fullname" . }}
  labels:
    {{- include "godebug.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.debugPort }}
      targetPort: http-debug
      protocol: TCP
      name: http-debug
  selector:
    {{- include "godebug.selectorLabels" . | nindent 4 }}
